#include <iostream>
#include <string>
#include <cstring>
#include <vector>
#include <algorithm>

using namespace std;

string binary__search(vector<string>::iterator first, vector<string>::iterator end, const string elem)
{
    if (first > end)
        return "None";

    vector<string>::iterator it = first + (end - first)/2;
    int res = strcmp(elem.c_str(), it->c_str());

    if (res == 0)
    {
        return *it;
    }
    else if (res < 0)
    {
        // Elem is in lower half
        return binary__search(first, it, elem);
    }
    else
    {
        return binary__search(it + 1, end, elem);
    }
    
    
}

int main()
{
    vector<string> vs = { "/home/", "/home/ritsz", "/initrd.img", "/var", "/opt", "/mnt",
                "/rut", "/lost+ftund", "/syt", "/ttp", "/utr", "/lit64", "/bttt", "/btot",
                "/lib", "/vmlinuz", "/root", "/proc", "/media", "/sbin", "/etc", "/cdrom",
                "/run", "/lost+found", "/sys", "/tmp", "/usr", "/lib64", "/boot", "/boot",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/rut", "/lost+ftund", "/syt", "/ttp", "/utr", "/lit64", "/bttt", "/btot",
                "/lib", "/vmlinuz", "/root", "/proc", "/media", "/sbin", "/etc", "/cdrom",
                "/run", "/lost+found", "/sys", "/tmp", "/usr", "/lib64", "/boot", "/boot",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/rut", "/lost+ftund", "/syt", "/ttp", "/utr", "/lit64", "/bttt", "/btot",
                "/lib", "/vmlinuz", "/root", "/proc", "/media", "/sbin", "/etc", "/cdrom",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/rut", "/lost+ftund", "/syt", "/ttp", "/utr", "/lit64", "/bttt", "/btot",
                "/lib", "/vmlinuz", "/root", "/proc", "/media", "/sbin", "/etc", "/cdrom",
                "/run", "/lost+found", "/sys", "/tmp", "/usr", "/lib64", "/boot", "/boot",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/rut", "/lost+ftund", "/syt", "/ttp", "/utr", "/lit64", "/bttt", "/btot",
                "/lib", "/vmlinuz", "/root", "/proc", "/media", "/sbin", "/etc", "/cdrom",
                "/run", "/lost+found", "/sys", "/tmp", "/usr", "/lib64", "/boot", "/boot",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/rut", "/lost+ftund", "/syt", "/ttp", "/utr", "/lit64", "/bttt", "/btot",
                "/lib", "/vmlinuz", "/root", "/proc", "/media", "/sbin", "/etc", "/cdrom",
                "/run", "/lost+found", "/sys", "/tmp", "/usr", "/lib64", "/boot", "/boot",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/rut", "/lost+ftund", "/syt", "/ttp", "/utr", "/lit64", "/bttt", "/btot",
                "/lib", "/vmlinuz", "/root", "/proc", "/media", "/sbin", "/etc", "/cdrom",
                "/run", "/lost+found", "/sys", "/tmp", "/usr", "/lib64", "/boot", "/boot",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/rut", "/lost+ftund", "/syt", "/ttp", "/utr", "/lit64", "/bttt", "/btot",
                "/lib", "/vmlinuz", "/root", "/proc", "/media", "/sbin", "/etc", "/cdrom",
                "/run", "/lost+found", "/sys", "/tmp", "/usr", "/lib64", "/boot", "/boot",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/rut", "/lost+ftund", "/syt", "/ttp", "/utr", "/lit64", "/bttt", "/btot",
                "/lib", "/vmlinuz", "/root", "/proc", "/media", "/sbin", "/etc", "/cdrom",
                "/run", "/lost+found", "/sys", "/tmp", "/usr", "/lib64", "/boot", "/boot",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/rut", "/lost+ftund", "/syt", "/ttp", "/utr", "/lit64", "/bttt", "/btot",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/rut", "/lost+ftund", "/syt", "/ttp", "/utr", "/lit64", "/bttt", "/btot",
                "/lib", "/vmlinuz", "/root", "/proc", "/media", "/sbin", "/etc", "/cdrom",
                "/run", "/lost+found", "/sys", "/tmp", "/usr", "/lib64", "/boot", "/boot",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/rut", "/lost+ftund", "/syt", "/ttp", "/utr", "/lit64", "/bttt", "/btot",
                "/lib", "/vmlinuz", "/root", "/proc", "/media", "/sbin", "/etc", "/cdrom",
                "/run", "/lost+found", "/sys", "/tmp", "/usr", "/lib64", "/boot", "/boot",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/rut", "/lost+ftund", "/syt", "/ttp", "/utr", "/lit64", "/bttt", "/btot",
                "/lib", "/vmlinuz", "/root", "/proc", "/media", "/sbin", "/etc", "/cdrom",
                "/run", "/lost+found", "/sys", "/tmp", "/usr", "/lib64", "/boot", "/boot",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/rut", "/lost+ftund", "/syt", "/ttp", "/utr", "/lit64", "/bttt", "/btot",
                "/lib", "/vmlinuz", "/root", "/proc", "/media", "/sbin", "/etc", "/cdrom",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/rut", "/lost+ftund", "/syt", "/ttp", "/utr", "/lit64", "/bttt", "/btot",
                "/lib", "/vmlinuz", "/root", "/proc", "/media", "/sbin", "/etc", "/cdrom",
                "/run", "/lost+found", "/sys", "/tmp", "/usr", "/lib64", "/boot", "/boot",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/rut", "/lost+ftund", "/syt", "/ttp", "/utr", "/lit64", "/bttt", "/btot",
                "/lib", "/vmlinuz", "/root", "/proc", "/media", "/sbin", "/etc", "/cdrom",
                "/run", "/lost+found", "/sys", "/tmp", "/usr", "/lib64", "/boot", "/boot",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/rut", "/lost+ftund", "/syt", "/ttp", "/utr", "/lit64", "/bttt", "/btot",
                "/lib", "/vmlinuz", "/root", "/proc", "/media", "/sbin", "/etc", "/cdrom",
                "/run", "/lost+found", "/sys", "/tmp", "/usr", "/lib64", "/boot", "/boot",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/rut", "/lost+ftund", "/syt", "/ttp", "/utr", "/lit64", "/bttt", "/btot",
                "/lib", "/vmlinuz", "/root", "/proc", "/media", "/sbin", "/etc", "/cdrom",
                "/run", "/lost+found", "/sys", "/tmp", "/usr", "/lib64", "/boot", "/boot",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/rut", "/lost+ftund", "/syt", "/ttp", "/utr", "/lit64", "/bttt", "/btot",
                "/lib", "/vmlinuz", "/root", "/proc", "/media", "/sbin", "/etc", "/cdrom",
                "/run", "/lost+found", "/sys", "/tmp", "/usr", "/lib64", "/boot", "/boot",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/rut", "/lost+ftund", "/syt", "/ttp", "/utr", "/lit64", "/bttt", "/btot",
                "/lib", "/vmlinuz", "/root", "/proc", "/media", "/sbin", "/etc", "/cdrom",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/rut", "/lost+ftund", "/syt", "/ttp", "/utr", "/lit64", "/bttt", "/btot",
                "/lib", "/vmlinuz", "/root", "/proc", "/media", "/sbin", "/etc", "/cdrom",
                "/run", "/lost+found", "/sys", "/tmp", "/usr", "/lib64", "/boot", "/boot",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/rut", "/lost+ftund", "/syt", "/ttp", "/utr", "/lit64", "/bttt", "/btot",
                "/lib", "/vmlinuz", "/root", "/proc", "/media", "/sbin", "/etc", "/cdrom",
                "/run", "/lost+found", "/sys", "/tmp", "/usr", "/lib64", "/boot", "/boot",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/rut", "/lost+ftund", "/syt", "/ttp", "/utr", "/lit64", "/bttt", "/btot",
                "/lib", "/vmlinuz", "/root", "/proc", "/media", "/sbin", "/etc", "/cdrom",
                "/run", "/lost+found", "/sys", "/tmp", "/usr", "/lib64", "/boot", "/boot",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/rut", "/lost+ftund", "/syt", "/ttp", "/utr", "/lit64", "/bttt", "/btot",
                "/lib", "/vmlinuz", "/root", "/proc", "/media", "/sbin", "/etc", "/cdrom",
                "/run", "/lost+found", "/sys", "/tmp", "/usr", "/lib64", "/boot", "/boot",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/rut", "/lost+ftund", "/syt", "/ttp", "/utr", "/lit64", "/bttt", "/btot",
                "/lib", "/vmlinuz", "/root", "/proc", "/media", "/sbin", "/etc", "/cdrom",
                "/run", "/lost+found", "/sys", "/tmp", "/usr", "/lib64", "/boot", "/boot",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/rut", "/lost+ftund", "/syt", "/ttp", "/utr", "/lit64", "/bttt", "/btot",
                "/lib", "/vmlinuz", "/root", "/proc", "/media", "/sbin", "/etc", "/cdrom",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/rut", "/lost+ftund", "/syt", "/ttp", "/utr", "/lit64", "/bttt", "/btot",
                "/lib", "/vmlinuz", "/root", "/proc", "/media", "/sbin", "/etc", "/cdrom",
                "/run", "/lost+found", "/sys", "/tmp", "/usr", "/lib64", "/boot", "/boot",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/rut", "/lost+ftund", "/syt", "/ttp", "/utr", "/lit64", "/bttt", "/btot",
                "/lib", "/vmlinuz", "/root", "/proc", "/media", "/sbin", "/etc", "/cdrom",
                "/run", "/lost+found", "/sys", "/tmp", "/usr", "/lib64", "/boot", "/boot",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/rut", "/lost+ftund", "/syt", "/ttp", "/utr", "/lit64", "/bttt", "/btot",
                "/lib", "/vmlinuz", "/root", "/proc", "/media", "/sbin", "/etc", "/cdrom",
                "/run", "/lost+found", "/sys", "/tmp", "/usr", "/lib64", "/boot", "/boot",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/rut", "/lost+ftund", "/syt", "/ttp", "/utr", "/lit64", "/bttt", "/btot",
                "/lib", "/vmlinuz", "/root", "/proc", "/media", "/sbin", "/etc", "/cdrom",
                "/run", "/lost+found", "/sys", "/tmp", "/usr", "/lib64", "/boot", "/boot",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/rut", "/lost+ftund", "/syt", "/ttp", "/utr", "/lit64", "/bttt", "/btot",
                "/lib", "/vmlinuz", "/root", "/proc", "/media", "/sbin", "/etc", "/cdrom",
                "/run", "/lost+found", "/sys", "/tmp", "/usr", "/lib64", "/boot", "/boot",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/rut", "/lost+ftund", "/syt", "/ttp", "/utr", "/lit64", "/bttt", "/btot",
                "/lib", "/vmlinuz", "/root", "/proc", "/media", "/sbin", "/etc", "/cdrom",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/rut", "/lost+ftund", "/syt", "/ttp", "/utr", "/lit64", "/bttt", "/btot",
                "/lib", "/vmlinuz", "/root", "/proc", "/media", "/sbin", "/etc", "/cdrom",
                "/run", "/lost+found", "/sys", "/tmp", "/usr", "/lib64", "/boot", "/boot",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/rut", "/lost+ftund", "/syt", "/ttp", "/utr", "/lit64", "/bttt", "/btot",
                "/lib", "/vmlinuz", "/root", "/proc", "/media", "/sbin", "/etc", "/cdrom",
                "/run", "/lost+found", "/sys", "/tmp", "/usr", "/lib64", "/boot", "/boot",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/rut", "/lost+ftund", "/syt", "/ttp", "/utr", "/lit64", "/bttt", "/btot",
                "/lib", "/vmlinuz", "/root", "/proc", "/media", "/sbin", "/etc", "/cdrom",
                "/run", "/lost+found", "/sys", "/tmp", "/usr", "/lib64", "/boot", "/boot",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/rut", "/lost+ftund", "/syt", "/ttp", "/utr", "/lit64", "/bttt", "/btot",
                "/lib", "/vmlinuz", "/root", "/proc", "/media", "/sbin", "/etc", "/cdrom",
                "/run", "/lost+found", "/sys", "/tmp", "/usr", "/lib64", "/boot", "/boot",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/rut", "/lost+ftund", "/syt", "/ttp", "/utr", "/lit64", "/bttt", "/btot",
                "/lib", "/vmlinuz", "/root", "/proc", "/media", "/sbin", "/etc", "/cdrom",
                "/run", "/lost+found", "/sys", "/tmp", "/usr", "/lib64", "/boot", "/boot",
                "/tib", "/tmlinuz", "/toot", "/troc", "/tedia", "/stin", "/ttc", "/tdrom",
                "/rut", "/lost+ftund", "/syt", "/ttp", "/utr", "/lit64", "/bttt", "/btot",
                "/rut", "/lost+ftund", "/syt", "/ttp", "/zvtrzzzzz", "/lit64", "/bttt", "/btot",
                "/bin", "/srv", "/dev" };

    std::sort(vs.begin(), vs.end());

    for (vector<string>::iterator it = vs.begin(); it < vs.end(); it += 1)
    {
        /*for (string s : vs)
        {
            if(strcmp(it->c_str(), s.c_str()) == 0)
            {
                res = *it;
                break;
            }
        }
        */
        
        auto res = binary_search(vs.begin(), vs.end(), *it);
        cout << res << endl;
    }
}
